midexamLam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('votes/', include('votes.urls'))
]

votes/urls.py
from django.urls import path
from . import views

app_name = 'votes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:votes_id>/', views.candidate_detail, name='detail'),
    #path('<int:votes_id>/update', views.update, name='update'),
    path('create/', views.candidate_create, name = 'create'),
    path('position/', views.position_create, name = 'position'),

]

votes/models.py
from django.db import models
from datetime import datetime

# Create your models here
class Candidate(models.Model):
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    #position = models.ForeignKey('Position', on_delete = models.CASCADE, null = True, blank = True)
    birthdate = models.DateField()
    platform = models.TextField()


class Position(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

class Vote(models.Model):
    candidate = models.ForeignKey('Candidate', on_delete = models.CASCADE, null = True, blank = True, related_name = 'vote')
    vote_datetime = models.DateTimeField(default=datetime.now())
    votes = models.IntegerField(default=0)

votes/forms.py
from django.forms import ModelForm
from .models import Candidate, Position

class CandidateModelForm(ModelForm):
    class Meta:
        model = Candidate
        exclude = ['id']

class PositionModelForm(ModelForm):
    class Meta:
        model = Position
        exclude = ['id']

votes/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Candidate, Position, Vote
from .forms import CandidateModelForm, PositionModelForm
from datetime import datetime
# Create your views here.

def index(request):
    cands = {}
    candidate = Candidate.objects.all()
    #vote = Vote.objects.all()
    cands['candidate'] = candidate
    #cands['vote'] = vote
    return render(request,'index.html',cands)


def candidate_detail(request, votes_id):
    cands = {}
    cands['candidate'] = Candidate.objects.get(id=votes_id)
    return render(request, 'detail.html', cands)


def candidate_create(request):
    cands = {}
    cands['form'] = CandidateModelForm()
    if request.method == 'POST':
        form = CandidateModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/votes/')
        else:
            cands['form'] = form
            render(request, 'create.html', cands)
    else:
        return render(request, 'create.html', cands)


def candidate_update(request):
    cands = {}
    candidate = Candidate.objects.get(id=votes_id)
    if request.method == 'POST':
        form = CandidateModelForm(request.POST, instance=candidate)
        if form.is_valid():
            form.save()
            return HttpResponse('Candidate updated')
        else:
            cands['form'] = form
            render(request, 'update.html', cands)
    else:
        #question = Question.objects.get(id=question_id)
        cands['form'] = PostModelForm(instance=candidate)
        #context['q_id'] = question_id
    return render(request, 'update.html', cands)


def position_create(request):
    pos = {}
    pos['form'] = PositionModelForm()
    if request.method == 'POST':
        form = PositionModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/votes/')
        else:
            pos['form'] = form
            render(request, 'position.html', pos)
    else:
        return render(request, 'position.html', pos)

def vote(request, votes_id):
    cands = Candidate.objects.get(id=candidate_id)
    cands.vote.all().count()

votes/templates/base.html
{% load static %}
<html>
  <head>
    <title>
      {% block head %}
        This is the title head
      {% endblock %}
    </title>
    <link rel = "stylesheet" type="text/css" href="{% static 'votes/materialize/css/materialize.min.css' %}">
    {% block styles %}
    {% endblock %}
  </head>
  <body>
    {% block body %}
      123456
    {% endblock %}
    <script src = "{% static 'votes/materialize/js/materialize.min.js' %}"></script>
    {% block scripts %}
    {% endblock %}
  </body>
</html>

votes/templates/create.html
{% extends 'base.html' %}

{% block head %}
  Create Candidate
{% endblock %}

{% block body %}
<form action="{% url 'votes:create' %}" method="POST">
  {% csrf_token %}
  {% for field in form %}
    {{ field.errors }}
    {{ field.label }} {{ field }}
  {% endfor %}
  <input type = "submit" value = "Create">
</form>
{% endblock %}

votes/templates/detail.html
{% extends 'base.html' %}

{% block head %}
  Detail page
{% endblock %}

{% block body %}
  Lastname: {{ candidate.lastname }} <br/>
  Firstname: {{ candidate.firstname }} <br/>
  Birthdate: {{ candidate.birthdate }} <br/>
  <br />


{% endblock body %}

votes/templates/index.html
{% extends 'base.html' %}

{% block head %}
  Index Page
{% endblock %}

{% block body %}

  <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Logo</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="sass.html">Sass</a></li>
        <li><a href="badges.html">Components</a></li>
        <li><a href="collapsible.html">JavaScript</a></li>
      </ul>
    </div>
  </nav>

{% for a in candidate %}
  <div class = "row">
    <div class = "col s12 m6">
      <div class = "card blue-grey darken-1">
        <div class = "card-content white-text">
          <span class = "card-title">{{ a.lastname }}, {{ a.firstname }}</span>
          <p>Position:</p> <br/>
        </div>
        <div class = "card-action">
          <a href="{% url 'votes:detail' a.id %}">Detail Page</a>
        </div>
      </div>
    </div>
  </div>
{% endfor %}
{% for vote in candidate.vote.all %}
  Vote Count: {{ vote.votes }}
{% endfor %}
<a class = "waves-effect waves-light btn" href="{% url 'votes:create' %}">Create Candidate</a>
<a class = "waves-effect waves-light btn" href="{% url 'votes:position' %}">Create Position</a>
{% endblock body %}

votes/templates/position.html
{% extends 'base.html' %}

{% block head %}
  Create Position
{% endblock %}

{% block body %}
<form action="{% url 'votes:position' %}" method="POST">
  {% csrf_token %}
  {% for field in form %}
    {{ field.errors }}
    {{ field.label }} {{ field }}
  {% endfor %}
  <input type = "submit" value = "Create">
</form>
{% endblock %}

votes/templates/update.html
{% extends 'base.html' %}

{% block head %}
  Update Page
{% endblock %}

{% block body %}
<form action="{% url 'votes:update' form.instance.id %}" method="POST">
  {% csrf_token %}
  {% for field in form %}
    {{ field.errors }}
    {{ field.label }} {{ field }}
  {% endfor %}
  <input type = "submit" value = "Update">
</form>
{% endblock %}